version: "3"

services:
  scrapyd:
    build: ./scrapyd/
    ports:
      - "6800:6800"
    volumes:
      - scrapyd-volume:/scrapyd:Z
  scrapydweb:
    build: ./scrapydweb/
    depends_on:
      - scrapyd
    links:
      - scrapyd
    ports:
      - "5000:5000"
    environment:
      - SCRAPYD_SERVERS=scrapyd
    restart: unless-stopped

volumes:
  scrapyd-volume:
